# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from capstone.decorators import lazy_property
from capstone.configuration import Configuration
from capstone.configuration import Environment
from capstone.controllers.login_controller import LoginController
from capstone.controllers.usuarios_controller import UsuariosController
from capstone.controllers.gerentes_controller import GerentesController
from capstone.controllers.garcons_controller import GarconsController
from capstone.controllers.operadores_controller import OperadoresController
from capstone.controllers.fornecedores_controller import FornecedoresController
from capstone.controllers.fornecedor_produto_controller\
    import FornecedorProdutoController
from capstone.controllers.forma_de_pagamento_controller\
    import FormaDePagamentoController
from capstone.controllers.mesas_controller import MesasController
from capstone.controllers.contas_controller import ContasController
from capstone.controllers.produtos_controller import ProdutosController
from capstone.controllers.conta_produto_controller\
    import ContaProdutoController
from capstone.controllers.caixa_controller import CaixaController
from capstone.controllers.operador_caixa_controller\
    import OperadorCaixaController
from capstone.controllers.ordens_de_compra_controller\
    import OrdensDeCompraController
from capstone.controllers.produtos_das_ordens_de_compra_controller\
    import ProdutosDasOrdensDeCompraController


class CapstoneClient(object):

    @lazy_property
    def login(self):
        return LoginController(self.config)

    @lazy_property
    def usuarios(self):
        return UsuariosController(self.config)

    @lazy_property
    def gerentes(self):
        return GerentesController(self.config)

    @lazy_property
    def garcons(self):
        return GarconsController(self.config)

    @lazy_property
    def operadores(self):
        return OperadoresController(self.config)

    @lazy_property
    def fornecedores(self):
        return FornecedoresController(self.config)

    @lazy_property
    def fornecedor_produto(self):
        return FornecedorProdutoController(self.config)

    @lazy_property
    def forma_de_pagamento(self):
        return FormaDePagamentoController(self.config)

    @lazy_property
    def mesas(self):
        return MesasController(self.config)

    @lazy_property
    def contas(self):
        return ContasController(self.config)

    @lazy_property
    def produtos(self):
        return ProdutosController(self.config)

    @lazy_property
    def conta_produto(self):
        return ContaProdutoController(self.config)

    @lazy_property
    def caixa(self):
        return CaixaController(self.config)

    @lazy_property
    def operador_caixa(self):
        return OperadorCaixaController(self.config)

    @lazy_property
    def ordens_de_compra(self):
        return OrdensDeCompraController(self.config)

    @lazy_property
    def produtos_das_ordens_de_compra(self):
        return ProdutosDasOrdensDeCompraController(self.config)

    def __init__(self, timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION,
                 access_token='TODO: Replace', config=None):
        if config is None:
            self.config = Configuration(timeout=timeout,
                                        max_retries=max_retries,
                                        backoff_factor=backoff_factor,
                                        retry_statuses=retry_statuses,
                                        retry_methods=retry_methods,
                                        environment=environment,
                                        access_token=access_token)
        else:
            self.config = config
