# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlterarProdutoOrdemDeCompraRequest(object):

    """Implementation of the 'Alterar produto ordem de compraRequest' model.

    TODO: type model description here.

    Attributes:
        cost (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cost": 'cost'
    }

    def __init__(self,
                 cost=None):
        """Constructor for the AlterarProdutoOrdemDeCompraRequest class"""

        # Initialize members of the class
        self.cost = cost

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        cost = dictionary.get('cost')

        # Return an object of this model
        return cls(cost)
