# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlterarCaixaRequest(object):

    """Implementation of the 'Alterar caixaRequest' model.

    TODO: type model description here.

    Attributes:
        balance (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "balance": 'balance'
    }

    def __init__(self,
                 balance=None):
        """Constructor for the AlterarCaixaRequest class"""

        # Initialize members of the class
        self.balance = balance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        balance = dictionary.get('balance')

        # Return an object of this model
        return cls(balance)
