# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlterarGarcomRequest(object):

    """Implementation of the 'Alterar garcomRequest' model.

    TODO: type model description here.

    Attributes:
        cpf (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cpf": 'cpf'
    }

    def __init__(self,
                 cpf=None):
        """Constructor for the AlterarGarcomRequest class"""

        # Initialize members of the class
        self.cpf = cpf

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        cpf = dictionary.get('cpf')

        # Return an object of this model
        return cls(cpf)
