# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlterarFornecedorRequest1(object):

    """Implementation of the 'Alterar fornecedorRequest1' model.

    TODO: type model description here.

    Attributes:
        id_product (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id_product": 'id_product'
    }

    def __init__(self,
                 id_product=None):
        """Constructor for the AlterarFornecedorRequest1 class"""

        # Initialize members of the class
        self.id_product = id_product

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id_product = dictionary.get('id_product')

        # Return an object of this model
        return cls(id_product)
