# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AlterarContaRequest(object):

    """Implementation of the 'Alterar contaRequest' model.

    TODO: type model description here.

    Attributes:
        id_mesa (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id_mesa": 'id_mesa'
    }

    def __init__(self,
                 id_mesa=None):
        """Constructor for the AlterarContaRequest class"""

        # Initialize members of the class
        self.id_mesa = id_mesa

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id_mesa = dictionary.get('id_mesa')

        # Return an object of this model
        return cls(id_mesa)
