# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarOrdemDeCompraRequest(object):

    """Implementation of the 'Criar ordem de compraRequest' model.

    TODO: type model description here.

    Attributes:
        id_manager (int): TODO: type description here.
        id_provider (int): TODO: type description here.
        date (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id_manager": 'id_manager',
        "id_provider": 'id_provider',
        "date": 'date'
    }

    def __init__(self,
                 id_manager=None,
                 id_provider=None,
                 date=None):
        """Constructor for the CriarOrdemDeCompraRequest class"""

        # Initialize members of the class
        self.id_manager = id_manager
        self.id_provider = id_provider
        self.date = date

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id_manager = dictionary.get('id_manager')
        id_provider = dictionary.get('id_provider')
        date = dictionary.get('date')

        # Return an object of this model
        return cls(id_manager,
                   id_provider,
                   date)
