# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarFornecedorRequest(object):

    """Implementation of the 'Criar fornecedorRequest' model.

    TODO: type model description here.

    Attributes:
        trading_name (string): TODO: type description here.
        cnpj (string): TODO: type description here.
        phone (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "trading_name": 'trading_name',
        "cnpj": 'cnpj',
        "phone": 'phone'
    }

    def __init__(self,
                 trading_name=None,
                 cnpj=None,
                 phone=None):
        """Constructor for the CriarFornecedorRequest class"""

        # Initialize members of the class
        self.trading_name = trading_name
        self.cnpj = cnpj
        self.phone = phone

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        trading_name = dictionary.get('trading_name')
        cnpj = dictionary.get('cnpj')
        phone = dictionary.get('phone')

        # Return an object of this model
        return cls(trading_name,
                   cnpj,
                   phone)
