# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarContaProdutoRequest(object):

    """Implementation of the 'Criar conta produtoRequest' model.

    TODO: type model description here.

    Attributes:
        id_account (string): TODO: type description here.
        id_product (string): TODO: type description here.
        quantity (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id_account": 'id_account',
        "id_product": 'id_product',
        "quantity": 'quantity'
    }

    def __init__(self,
                 id_account=None,
                 id_product=None,
                 quantity=None):
        """Constructor for the CriarContaProdutoRequest class"""

        # Initialize members of the class
        self.id_account = id_account
        self.id_product = id_product
        self.quantity = quantity

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id_account = dictionary.get('id_account')
        id_product = dictionary.get('id_product')
        quantity = dictionary.get('quantity')

        # Return an object of this model
        return cls(id_account,
                   id_product,
                   quantity)
