# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarContaRequest(object):

    """Implementation of the 'Criar contaRequest' model.

    TODO: type model description here.

    Attributes:
        date (string): TODO: type description here.
        id_cashier (int): TODO: type description here.
        id_waiter (int): TODO: type description here.
        id_table (int): TODO: type description here.
        id_payment_method (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date": 'date',
        "id_cashier": 'id_cashier',
        "id_waiter": 'id_waiter',
        "id_table": 'id_table',
        "id_payment_method": 'id_payment_method'
    }

    def __init__(self,
                 date=None,
                 id_cashier=None,
                 id_waiter=None,
                 id_table=None,
                 id_payment_method=None):
        """Constructor for the CriarContaRequest class"""

        # Initialize members of the class
        self.date = date
        self.id_cashier = id_cashier
        self.id_waiter = id_waiter
        self.id_table = id_table
        self.id_payment_method = id_payment_method

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        date = dictionary.get('date')
        id_cashier = dictionary.get('id_cashier')
        id_waiter = dictionary.get('id_waiter')
        id_table = dictionary.get('id_table')
        id_payment_method = dictionary.get('id_payment_method')

        # Return an object of this model
        return cls(date,
                   id_cashier,
                   id_waiter,
                   id_table,
                   id_payment_method)
