# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarMesaRequest(object):

    """Implementation of the 'Criar mesaRequest' model.

    TODO: type model description here.

    Attributes:
        number (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "number": 'number'
    }

    def __init__(self,
                 number=None):
        """Constructor for the CriarMesaRequest class"""

        # Initialize members of the class
        self.number = number

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        number = dictionary.get('number')

        # Return an object of this model
        return cls(number)
