# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarCaixaRequest(object):

    """Implementation of the 'Criar caixaRequest' model.

    TODO: type model description here.

    Attributes:
        initial_value (int): TODO: type description here.
        balance (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "initial_value": 'initial_value',
        "balance": 'balance'
    }

    def __init__(self,
                 initial_value=None,
                 balance=None):
        """Constructor for the CriarCaixaRequest class"""

        # Initialize members of the class
        self.initial_value = initial_value
        self.balance = balance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        initial_value = dictionary.get('initial_value')
        balance = dictionary.get('balance')

        # Return an object of this model
        return cls(initial_value,
                   balance)
