# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarFormaDePagamentoRequest(object):

    """Implementation of the 'Criar forma de pagamentoRequest' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "description": 'description'
    }

    def __init__(self,
                 name=None,
                 description=None):
        """Constructor for the CriarFormaDePagamentoRequest class"""

        # Initialize members of the class
        self.name = name
        self.description = description

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('name')
        description = dictionary.get('description')

        # Return an object of this model
        return cls(name,
                   description)
