# -*- coding: utf-8 -*-

"""
capstone

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CriarUsuarioRequest(object):

    """Implementation of the 'Criar usuarioRequest' model.

    TODO: type model description here.

    Attributes:
        username (string): TODO: type description here.
        mtype (int): TODO: type description here.
        password (string): TODO: type description here.
        name (string): TODO: type description here.
        cpf (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username": 'username',
        "mtype": 'type',
        "password": 'password',
        "name": 'name',
        "cpf": 'cpf'
    }

    def __init__(self,
                 username=None,
                 mtype=None,
                 password=None,
                 name=None,
                 cpf=None):
        """Constructor for the CriarUsuarioRequest class"""

        # Initialize members of the class
        self.username = username
        self.mtype = mtype
        self.password = password
        self.name = name
        self.cpf = cpf

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')
        mtype = dictionary.get('type')
        password = dictionary.get('password')
        name = dictionary.get('name')
        cpf = dictionary.get('cpf')

        # Return an object of this model
        return cls(username,
                   mtype,
                   password,
                   name,
                   cpf)
